# Generated by Django 3.2.14 on 2022-07-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='amount',
            new_name='quantity',
        ),
    ]
